template = ""
rev_id = 7
template_sha = "94893e7a5cd0adce3abaa3e278710450dd114995"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "lv"
__UND2C_TRG__ = "liv"
__UNDEFINED_SOURCE__ = "Latvian"
__UNDEFINED_TARGET__ = "Liv (Livonian)"
__UND_SRC__ = "lav"
__UND_TRG__ = "liv"
