template = ""
rev_id = 9
template_sha = "40afa223ab00844a035cff537a1d85d88c975bf8"

[replacements]
__LICENSE__ = "CC-BY-4.0"
__UND2C_SRC__ = "lv"
__UND2C_TRG__ = "liv"
__UNDEFINED_SOURCE__ = "Latvian"
__UNDEFINED_TARGET__ = "Liv (Livonian)"
__UND_SRC__ = "lav"
__UND_TRG__ = "liv"
